### GETTER FOR ROUTE ON -1 celler, een lijst van punten word teruggegeven omdat we tekenen in fronted
GET http://localhost:5028/api/path/route
Content-Type: application/json

{
  "Start": {
    "XWidth": 1507.0 , 
    "YHeight": 1148.0
  },
  "End": {
    "XWidth": 2096.0 ,
    "YHeight": 1466.0
  },
  "HospitalName": "UZ Groenplaats",
  "FloorName": "floor_minus1C.png"
}