// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWYFqsbgB3GWl0MWzu-ZBmYdG3cLnEQTk',
    appId: '1:64737425690:web:98045871e8651e8bd0d4a3',
    messagingSenderId: '64737425690',
    projectId: 'vitalroutes-58c59',
    authDomain: 'vitalroutes-58c59.firebaseapp.com',
    storageBucket: 'vitalroutes-58c59.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUZ_UbrzP-7-k0jaP1SwI3RK2XqkBLsBQ',
    appId: '1:64737425690:android:336e425c5e1713e8d0d4a3',
    messagingSenderId: '64737425690',
    projectId: 'vitalroutes-58c59',
    storageBucket: 'vitalroutes-58c59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDLX_ra097H64fRKESxm8rWgh-6IGcBcY',
    appId: '1:64737425690:ios:0faf3aeec7ace661d0d4a3',
    messagingSenderId: '64737425690',
    projectId: 'vitalroutes-58c59',
    storageBucket: 'vitalroutes-58c59.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDLX_ra097H64fRKESxm8rWgh-6IGcBcY',
    appId: '1:64737425690:ios:0faf3aeec7ace661d0d4a3',
    messagingSenderId: '64737425690',
    projectId: 'vitalroutes-58c59',
    storageBucket: 'vitalroutes-58c59.firebasestorage.app',
    iosBundleId: 'com.example.ui',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWYFqsbgB3GWl0MWzu-ZBmYdG3cLnEQTk',
    appId: '1:64737425690:web:d511c7408dcbfd0fd0d4a3',
    messagingSenderId: '64737425690',
    projectId: 'vitalroutes-58c59',
    authDomain: 'vitalroutes-58c59.firebaseapp.com',
    storageBucket: 'vitalroutes-58c59.firebasestorage.app',
  );
}
